name: fyndr
description: "A new Flutter project."


version: 1.0.0

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  marquee: ^2.3.0
  dotted_border: ^3.0.1
  icons_launcher: ^3.0.1
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  iconsax: ^0.0.8
  mime: ^2.0.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  url_launcher: ^6.3.1
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true





  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/gifs/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
